### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by mendeleev1337** [TrueCarry/JettonGramGpuMiner#2]
Node.js v20.11.0
Using givers 100
Using bin .\pow-miner-opencl.exe
Using GPU 0
Using timeout 5
Using TonHub API
C:\Users\proro\Downloads\JettonGramGpuMiner-main\JettonGramGpuMiner-main\send_universal.js:187
        const keyPair = yield (0, crypto_1.mnemonicToWalletKey)(mySeed.split(' '));
                                                                       ^

TypeError: Cannot read properties of undefined (reading 'split')
    at C:\Users\proro\Downloads\JettonGramGpuMiner-main\JettonGramGpuMiner-main\send_universal.js:187:72
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\proro\Downloads\JettonGramGpuMiner-main\JettonGramGpuMiner-main\send_universal.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

by @LOLLPOP123 (telegram)

**Comment by nessshon** [comment]
@mendeleev1337,

The script cannot locate your config.txt with the SEED phrase. You can directly specify this variable in your .bat file.

For example:

```bat
set SEED=word1 word2

call ".\npm_install.bat"

:_minerstart
node send_universal.js --api tonhub --givers 1000
goto _minerstart

pause
```
