### ISSUE TITLE
Ubuntu 18.04 pow-miner-cuda not work

### ISSUE THREAD

**Issue by AlexSpain** [TrueCarry/JettonGramGpuMiner#3]
./pow-miner-cuda 

./pow-miner-cuda: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./pow-miner-cuda)

./pow-miner-cuda: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ./pow-miner-cuda)

**Comment by lrdcxdes** [comment]
# Check GLIBC_2.29
ldd --version | head -n1

# Build GLIBC_2.29 from sources
sudo apt-get install gawk bison -y
wget -c https://ftp.gnu.org/gnu/glibc/glibc-2.34.tar.gz
tar -zxvf glibc-2.34.tar.gz && cd glibc-2.34
mkdir glibc-build && cd glibc-build
../configure --prefix=/opt/glibc-2.34
make 
sudo make install

**Comment by AlexSpain** [comment]
./pow-miner-cuda: relocation error: /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1: symbol pthread_getspecific version GLIBC_2.2.5 not defined in file libpthread.so.0 with link time reference
